Add bundle update and install to fixit

diff --git a/scripts/fixit b/scripts/fixit
--- a/scripts/fixit
+++ b/scripts/fixit
@@ -34,6 +34,22 @@ if [ $? -ne 0 ]; then
     exit 2
 fi
 
+echo "*** Bundle update and install..."
+
+# bundle update
+sudo su $WEBUSER -c "$SUPARAMS $BUNDLE update --quiet"
+if [ $? -ne 0 ]; then
+    echo "Failed!"
+    exit 6
+fi
+
+# bundle install
+sudo su $WEBUSER -c "$SUPARAMS $BUNDLE install --quiet"
+if [ $? -ne 0 ]; then
+    echo "Failed!"
+    exit 7
+fi
+
 # update database
 echo
 echo "*** Updating database..."
